language: ruby
cache: bundler
sudo: false

bundler_args: --without=development

script:
  - bundle exec rake test:unit
  - bundle exec rake style

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

rvm: 2.4.4
matrix:
  include:
    - env: VAGRANT_VERSION=v2.2.3
    - env: VAGRANT_VERSION=v2.0.4
    - env:
        - VAGRANT_VERSION=v1.9.8
      rvm: 2.2.5
    - env: VAGRANT_VERSION=master
  allow_failures:
    - env: VAGRANT_VERSION=master
